# version: '3.1'
name: 'crawler'
services:

  mongo:
    image: mongo
    container_name: crawler_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    container_name: crawler_mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:root@mongo:27017/
    volumes:
      - "./api:/flask/app"
  
  gradio:
    build:
      context: .
      dockerfile: gradio/Dockerfile
    restart: always
    ports:
      - 7860:7860
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:root@mongo:27017/
    volumes:
      - "./gradio:/gradio/app"