name: 'crawler'
services:

  mongo:
    image: mongo
    container_name: crawler_mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    container_name: crawler_mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:root@mongo:27017/
    volumes:
      - "./api:/flask/"

  vue:
    build:
      context: .
      dockerfile: vue_starter/Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - api
    volumes:
      - "./vue_starter/src:/app/src"
      - "./vue_starter/package.json:/app/package.json"
      - "./vue_starter/package-lock.json:/app/package-lock.json"


